language: android

addons:
    apt:
        packages:
        - libgd2-xpm
        - ia32-libs
        - ia32-libs-multiarch

android:
   components:
   - tools
   - platform-tools
   - android-23
   - build-tools-23.0.2
   - extra

jdk: oraclejdk7

notifications:
  email: false

before_install:
   - touch local.properties
   - source gradle.properties
   - openssl aes-256-cbc -K $encrypted_151cd4732554_key -iv $encrypted_151cd4732554_iv -in release.jks.enc -out release.jks -d

script:
  - ./gradlew clean assembleDebug
  - cp app/build/outputs/apk/Gallery-v$VERSION_NAME-debug.apk $HOME
  - ./gradlew clean assembleRelease
  - cp app/build/outputs/apk/Gallery-v$VERSION_NAME-release.apk $HOME
  - md5sum "$HOME/Gallery-v$VERSION_NAME-debug.apk"
  - md5sum "$HOME/Gallery-v$VERSION_NAME-release.apk"
  - sha1sum "$HOME/Gallery-v$VERSION_NAME-debug.apk"
  - sha1sum "$HOME/Gallery-v$VERSION_NAME-release.apk"

deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  file:
    - "$HOME/Gallery-v$VERSION_NAME-debug.apk"
    - "$HOME/Gallery-v$VERSION_NAME-release.apk"
  skip_cleanup: true
  on:
    tags: true

env:
  global:
    - secure: "qpE7NyROwPAmlBSgMtf2EjEqt7bMHgg2HP+bC+3BZX8CGvcuRZVUkg+g+ZXPt5pulHIXtSW3yE2gBCzve+ek8BzTX22G9tVLqhO4pykB/AQYi/4UVxCsIIZiDxPFrceGD910/N650qV0++PAigYxxrhgVmZcvvfwczn32H1/1sciLyAIa7BvJKg4RULccN7yiiJ5w//nygQDLQcNCgSAVeF+OUsMbl4CgSqiMqAL/T+xJTakjZBmoPzgXfXKD5aCVjmwOSkMzHh0LnBUqHYp4luMUwkCt5brAyYvwCEBHjWbHLAuyQXl26sIdxNCikJN/2I7Vu3kE6LlaBxpZwBwc5zlazjF6utGEc7Ht1co9rI/3/zrjeJbrc74n91YSefnBunueCzBfypJx1vX/yq5CrB/edSLOXmAiYIve7NQo0E+Mq5P8X54w4wq6FEgDj3478z2oh6xAcukFloWAyuf+g6j8/B+2/gxtbWIXjtpaAwDgdDCXO6ViYGjvSJEe07P2VTFTn1FytTx2NpGynaEWiRJct2c4pGdXxNASMtXUqy8Tnl9gK1sWMmsdTBfbmBIH8iEy5IaKFAEaD8BzujGWWQG9cY9xC7nenZXE88xV9hCspJ/dTlQbz1M68t7mmxgz70BqnG6uONf6N92Viwc+DEZqpTLzHVTBUuUdfv0OuU="
    - secure: "yATjkRdXZrNxDQPXauzxyWEym72Wo/bprgEqAP6WOianWHPUAe7fb0sShdD6OnG7bFIagUeDZknDlhagEW8mfcpu5VlbhgC8AMIJe8JsmK982mXPoFhUcKKTDbN6Yc6ZySysli8IjvE+v1O/trJdl7f9Cv78NGKC8ES7hb3vRUFmn6YJxOx1unYeON0J9ubNSfsFx2aMeX4JC/P+BPUUmLL/b5T/fJNB7kirSGB5W/DsSKdRaYX5ZIEK4Yt/vribd+4AyAMj/p9yv+AFntlMLl9I75dsZzhZbMnZ5jxcWwDcFdFPvxnRnKDIMrfqbffcwpeIVp+utzBUiP/Cn7qDzlsvmFHjPjDzkdI0FaeFM3tHT1w/PWyI9wpszwdYt737PdaPBH3W91b5ZrrJU6Kvc/y1sagirks2qKPuReNLNPLIUAg80Sw09hvqsa0os7FWKn8lWeIn7ALeEvd502K/OenceMOHKYadromA/2/CV4Pu9BdFNGVZrLEOxKOXdHWdnlCR6qijsREyVnaYLvRDYMlOKajsoJu12ASVjfs0cpNic7fXiT86kMSYSZvkceYdaQEQifxVi8nGE4xwdvPXrf9h88Q3MLGyZ9sy4tSnTW1APcUalvQ5uh2pobx8v7SfP16ZLsvayKiBej0Z+ey1AC/n1iqZnMql09qlylP1Xb8="
    - secure: "js2QqxJpoA/MJs7Y6Jc5i4Sj3r1RzKshwjdu1B4WE6YpgWZ+us/dtmhSaeLxY7D5+mi9zS5hVRUNxKpy8AZvLbDoMykngUA1TUY/1+4RFOOJADqOLWgLmXnkX3V9tqJjxOC/Zs4+NfWTxQl/E5Ahsq4Qk7JyTQpJxf3S2fbY2VemaW2udOJjrFfAxLW4S8XJjH3FLBe4EyBKKzkzX1aQjXglbXXgnB6OHNTj6ojYp6m/6jU8cBn0B8h5nUG32KKPMx+mg6JODfBAs8sbfKG48e30412juHMy4gUT9Hx+isQmIJV497LLjs1I8f18VjuD2yvZliq5H5L19pwQROiTahwgqfYs2AuSodBIq6CCUb/+Lnu9zVfYtvTjhm1RfQoUbJkqSQWrvOmweAulqbtn92gkxS5cyxr+FHopMAbWznyfnbDDwf0iFgmZwjg9zaXtdgnlKk5SAlP0PXhfJtZUkNiabVuHcvLkur6FUl/sYkFAOfVGweAMVRV6gFOcTTfBxilRXj1JVXLCkoLjCXxT2WtWjCikWfcChNSo8MhHkF/LWR1zLijCK7AxU2Zpr+uAzKcf9dWGfsgJp2ZgZzSuuRPsyolQeHTcveIhUbElueP3o9h/igTKyjzQhylUHsLfvZnjVBb0zkSX94ANnkyI9/qRhAC7kC8VAQxkrlR1rmM="
    - secure: "zuD3FwahzEs/Lpm6syzZr9f0/RvjFVBXA8AlIwRG7WOumjcr5jQG586rDHgDLaHkIs7h5uA9yz7ZPehVJ94z3MDt63l7K/YeXjqnM36t8JzssD74oqSZmPenFrJmUay/INfR/PAeX/IvufUvVgn7aO+QfoUYgAtQ2PLXH7gciH0hhxNg1H0rjva48nN0L8A2EtqFvKWK2aide+Fv9cdgvEClfTRmJwf4oZkeYyEpTu2f5QYLUwPhH1F45552Lol7lzQajMUeCXx07GcS0nC98pyCRYgUkmyOnUZmGnib2z9hheLeDGvOrzKpQS6faLKLAa9nDzu1zqyrJPUve4FsXN9m06QjYQD3Wfz1yJIesnfUY+QCS1pn5sVh8h6wiy0rcRVbSvRfRgEhoH4EuIWVq+JhDpMLh3CwIgyd+X/NVREL1EB4rfCnphtbY//mgODUksWPbxU4cCvFIkiDJ2PaGToKjERwm3ZUaX89NeCWBK1IvHUUlFSg3mzogB0TDsmZr9V9isYk6mbo02oIELcrmIBZhzR3urEF+aLLK899sFNwkiui7wbCJ+zsAwaOmwV9kDUmFdPDd3ahKlfroQQ2b9+N14KOncK4stuffiunTEwIk8MswEbZyFmA4Fr45zjI0J8igcDXO8iIMU947J3++BKCpJThtsAg1ABl9Ru3+6k="
